/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VoteType = IDL.Variant({
  'upvote' : IDL.Null,
  'downvote' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const FeaturedContent = IDL.Record({
  'title' : IDL.Text,
  'externalLink' : IDL.Text,
  'featuredType' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const LinkType = IDL.Variant({
  'pdf' : IDL.Null,
  'patreon' : IDL.Null,
  'linktree' : IDL.Null,
  'twitter' : IDL.Null,
  'other' : IDL.Null,
  'blog' : IDL.Null,
  'etsy' : IDL.Null,
  'instagram' : IDL.Null,
  'substack' : IDL.Null,
  'website' : IDL.Null,
  'shopify' : IDL.Null,
  'booking' : IDL.Null,
  'calendly' : IDL.Null,
  'donation' : IDL.Null,
  'store' : IDL.Null,
  'facebook' : IDL.Null,
  'gumroad' : IDL.Null,
  'events' : IDL.Null,
  'discord' : IDL.Null,
  'youtube' : IDL.Null,
  'signal' : IDL.Null,
  'newsletter' : IDL.Null,
  'telegram' : IDL.Null,
});
export const ConnectedPresenceLink = IDL.Record({
  'url' : IDL.Text,
  'displayLabel' : IDL.Opt(IDL.Text),
  'linkType' : LinkType,
});
export const MemberInput = IDL.Record({
  'region' : IDL.Opt(IDL.Text),
  'paymentQrImage' : IDL.Opt(IDL.Text),
  'latitude' : IDL.Opt(IDL.Float64),
  'contactName' : IDL.Text,
  'paymentInstructions' : IDL.Opt(IDL.Text),
  'province' : IDL.Text,
  'acceptsBitcoin' : IDL.Bool,
  'subcategory' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'postalCode' : IDL.Opt(IDL.Text),
  'socialLinks' : IDL.Opt(IDL.Text),
  'acceptsCash' : IDL.Bool,
  'acceptsFiat' : IDL.Bool,
  'participantType' : IDL.Text,
  'circularEconomyParticipant' : IDL.Bool,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'featuredContent' : IDL.Opt(FeaturedContent),
  'email' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'connectedPresence' : IDL.Opt(IDL.Vec(ConnectedPresenceLink)),
  'longitude' : IDL.Opt(IDL.Float64),
  'bitcoinAddress' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'oisyWalletLink' : IDL.Opt(IDL.Text),
  'acceptsICP' : IDL.Bool,
  'icpAddress' : IDL.Opt(IDL.Text),
});
export const MemberParticipantType = IDL.Variant({
  'business' : IDL.Null,
  'organization' : IDL.Null,
  'individual' : IDL.Null,
  'producer' : IDL.Null,
});
export const MembershipTier = IDL.Variant({
  'localProducer' : IDL.Null,
  'builderMember' : IDL.Null,
  'localSponsor' : IDL.Null,
  'verifiedBusiness' : IDL.Null,
  'communitySupporterTier' : IDL.Null,
  'communityPartner' : IDL.Null,
});
export const MembershipIntentInput = IDL.Record({
  'principal' : IDL.Opt(IDL.Principal),
  'province' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'participantType' : MemberParticipantType,
  'email' : IDL.Text,
  'displayPublicly' : IDL.Bool,
  'message' : IDL.Opt(IDL.Text),
  'membershipTier' : MembershipTier,
});
export const MembershipStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'contacted' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const MembershipIntent = IDL.Record({
  'id' : IDL.Text,
  'status' : MembershipStatus,
  'principal' : IDL.Opt(IDL.Principal),
  'province' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'participantType' : MemberParticipantType,
  'email' : IDL.Text,
  'displayPublicly' : IDL.Bool,
  'message' : IDL.Opt(IDL.Text),
  'membershipTier' : MembershipTier,
});
export const Result__1 = IDL.Variant({
  'ok' : MembershipIntent,
  'err' : IDL.Text,
});
export const OpportunityStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const OpportunityCategory = IDL.Variant({
  'creativeArts' : IDL.Null,
  'localFarming' : IDL.Null,
  'other' : IDL.Null,
  'education' : IDL.Null,
  'technology' : IDL.Null,
  'foodSupport' : IDL.Null,
  'events' : IDL.Null,
  'wellness' : IDL.Null,
  'cleanup' : IDL.Null,
  'delivery' : IDL.Null,
  'youthSupport' : IDL.Null,
  'mentorship' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const OpportunityInput = IDL.Record({
  'status' : OpportunityStatus,
  'memberId' : IDL.Opt(IDL.Text),
  'organizationName' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'contactLink' : IDL.Opt(IDL.Text),
  'province' : IDL.Text,
  'city' : IDL.Text,
  'recurring' : IDL.Bool,
  'trustScore' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'chapterId' : IDL.Opt(IDL.Text),
  'timeCommitment' : IDL.Opt(IDL.Text),
  'category' : OpportunityCategory,
});
export const CommunityOpportunity = IDL.Record({
  'id' : IDL.Nat,
  'status' : OpportunityStatus,
  'memberId' : IDL.Opt(IDL.Text),
  'organizationName' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'contactLink' : IDL.Opt(IDL.Text),
  'province' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'recurring' : IDL.Bool,
  'trustScore' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'chapterId' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'timeCommitment' : IDL.Opt(IDL.Text),
  'category' : OpportunityCategory,
  'adminFlagged' : IDL.Opt(IDL.Bool),
});
export const Result_4 = IDL.Variant({
  'ok' : CommunityOpportunity,
  'err' : IDL.Text,
});
export const VolunteerInput = IDL.Record({
  'interests' : IDL.Vec(IDL.Text),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'availability' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const ActivityEvent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'province' : IDL.Text,
  'city' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'relatedListingId' : IDL.Opt(IDL.Text),
  'relatedChapterId' : IDL.Opt(IDL.Text),
  'eventType' : IDL.Text,
});
export const ListingMembershipStatus = IDL.Variant({
  'supporter' : IDL.Null,
  'businessMember' : IDL.Null,
  'free' : IDL.Null,
  'sponsor' : IDL.Null,
  'producerMember' : IDL.Null,
  'partner' : IDL.Null,
});
export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const MemberRecord = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Opt(IDL.Text),
  'paymentQrImage' : IDL.Opt(IDL.Text),
  'latitude' : IDL.Opt(IDL.Float64),
  'votingFrozen' : IDL.Bool,
  'featured' : IDL.Bool,
  'communityVerified' : IDL.Bool,
  'contactName' : IDL.Text,
  'paymentInstructions' : IDL.Opt(IDL.Text),
  'province' : IDL.Text,
  'acceptsBitcoin' : IDL.Bool,
  'subcategory' : IDL.Opt(IDL.Text),
  'communityVerificationStatus' : IDL.Text,
  'city' : IDL.Text,
  'ownerPrincipal' : IDL.Opt(IDL.Text),
  'postalCode' : IDL.Opt(IDL.Text),
  'socialLinks' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'acceptsCash' : IDL.Bool,
  'acceptsFiat' : IDL.Bool,
  'participantType' : IDL.Text,
  'circularEconomyParticipant' : IDL.Bool,
  'businessName' : IDL.Text,
  'description' : IDL.Text,
  'featuredContent' : IDL.Opt(FeaturedContent),
  'email' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'membershipStatus' : ListingMembershipStatus,
  'updatedAt' : Timestamp,
  'connectedPresence' : IDL.Vec(ConnectedPresenceLink),
  'longitude' : IDL.Opt(IDL.Float64),
  'bitcoinAddress' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'flaggedForReview' : IDL.Bool,
  'communityDownvotes' : IDL.Nat,
  'phone' : IDL.Opt(IDL.Text),
  'oisyWalletLink' : IDL.Opt(IDL.Text),
  'acceptsICP' : IDL.Bool,
  'icpAddress' : IDL.Opt(IDL.Text),
  'verificationStatus' : VerificationStatus,
  'communityUpvotes' : IDL.Nat,
});
export const AdminTrustQueue = IDL.Record({
  'highTrust' : IDL.Vec(MemberRecord),
  'pending' : IDL.Vec(MemberRecord),
  'flagged' : IDL.Vec(MemberRecord),
});
export const Result_3 = IDL.Variant({
  'ok' : AdminTrustQueue,
  'err' : IDL.Text,
});
export const CityStats = IDL.Record({
  'province' : IDL.Text,
  'producerCount' : IDL.Nat,
  'volunteerCount' : IDL.Nat,
  'businessCount' : IDL.Nat,
  'city' : IDL.Text,
  'memberCount' : IDL.Nat,
  'totalListings' : IDL.Nat,
});
export const TrustSummary = IDL.Record({
  'upvotes' : IDL.Nat,
  'callerVote' : IDL.Opt(VoteType),
  'downvotes' : IDL.Nat,
});
export const Result_2 = IDL.Variant({ 'ok' : TrustSummary, 'err' : IDL.Text });
export const SearchFilters = IDL.Record({
  'province' : IDL.Opt(IDL.Text),
  'acceptsBitcoin' : IDL.Opt(IDL.Bool),
  'city' : IDL.Opt(IDL.Text),
  'circularEconomyParticipant' : IDL.Opt(IDL.Bool),
  'category' : IDL.Opt(IDL.Text),
  'acceptsICP' : IDL.Opt(IDL.Bool),
  'verificationStatus' : IDL.Opt(VerificationStatus),
});
export const MembershipStats = IDL.Record({
  'byTier' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'total' : IDL.Nat,
  'estimatedMonthlySupport' : IDL.Nat,
  'byStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const StatsRecord = IDL.Record({
  'communityMembers' : IDL.Nat,
  'verifiedMembers' : IDL.Nat,
  'byProvince' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'circularEconomy' : IDL.Nat,
  'organizationPartners' : IDL.Nat,
  'bitcoinEnabled' : IDL.Nat,
  'producerMembers' : IDL.Nat,
  'pendingMembers' : IDL.Nat,
  'totalMembers' : IDL.Nat,
  'icpEnabled' : IDL.Nat,
  'businessMembers' : IDL.Nat,
  'tradeMembers' : IDL.Nat,
});
export const VolunteerInterest = IDL.Record({
  'id' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'availability' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addCommunityVote' : IDL.Func([IDL.Text, VoteType], [Result_1], []),
  'adminFlagOpportunity' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
  'approveMember' : IDL.Func([IDL.Text], [Result], []),
  'createMember' : IDL.Func([MemberInput], [Result_1], []),
  'createMembershipIntent' : IDL.Func([MembershipIntentInput], [Result__1], []),
  'createOpportunity' : IDL.Func([OpportunityInput], [Result_4], []),
  'createVolunteer' : IDL.Func([VolunteerInput], [Result_1], []),
  'deleteMember' : IDL.Func([IDL.Text], [Result], []),
  'featureMember' : IDL.Func([IDL.Text, IDL.Bool], [Result], []),
  'freezeVoting' : IDL.Func([IDL.Text, IDL.Bool], [Result_1], []),
  'getActivityFeed' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityEvent)], ['query']),
  'getAdminTrustQueue' : IDL.Func([], [Result_3], ['query']),
  'getCityStats' : IDL.Func([], [IDL.Vec(CityStats)], ['query']),
  'getCommunityVotes' : IDL.Func([IDL.Text], [Result_2], ['query']),
  'getLatestOpportunities' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CommunityOpportunity)],
      ['query'],
    ),
  'getLocalActivity' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(ActivityEvent)],
      ['query'],
    ),
  'getMember' : IDL.Func([IDL.Text], [IDL.Opt(MemberRecord)], ['query']),
  'getMembers' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(SearchFilters)],
      [IDL.Vec(MemberRecord)],
      ['query'],
    ),
  'getMembershipIntents' : IDL.Func([], [IDL.Vec(MembershipIntent)], ['query']),
  'getMembershipIntentsByStatus' : IDL.Func(
      [MembershipStatus],
      [IDL.Vec(MembershipIntent)],
      ['query'],
    ),
  'getMembershipIntentsByTier' : IDL.Func(
      [MembershipTier],
      [IDL.Vec(MembershipIntent)],
      ['query'],
    ),
  'getMembershipStats' : IDL.Func([], [MembershipStats], ['query']),
  'getMyVote' : IDL.Func([IDL.Text], [IDL.Opt(VoteType)], ['query']),
  'getOpportunities' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(OpportunityCategory),
        IDL.Opt(OpportunityStatus),
      ],
      [IDL.Vec(CommunityOpportunity)],
      ['query'],
    ),
  'getOpportunitiesByMember' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CommunityOpportunity)],
      ['query'],
    ),
  'getOpportunityById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CommunityOpportunity)],
      ['query'],
    ),
  'getPublicSupporters' : IDL.Func([], [IDL.Vec(MembershipIntent)], ['query']),
  'getStats' : IDL.Func([], [StatsRecord], []),
  'getVolunteers' : IDL.Func([], [IDL.Vec(VolunteerInterest)], []),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'overrideTrustStatus' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'rejectMember' : IDL.Func([IDL.Text], [Result], []),
  'removeCommunityVote' : IDL.Func([IDL.Text], [Result_1], []),
  'updateMember' : IDL.Func([IDL.Text, MemberInput], [Result], []),
  'updateMembershipIntentStatus' : IDL.Func(
      [IDL.Text, MembershipStatus],
      [Result__1],
      [],
    ),
  'updateOpportunityStatus' : IDL.Func(
      [IDL.Nat, OpportunityStatus],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VoteType = IDL.Variant({ 'upvote' : IDL.Null, 'downvote' : IDL.Null });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const FeaturedContent = IDL.Record({
    'title' : IDL.Text,
    'externalLink' : IDL.Text,
    'featuredType' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const LinkType = IDL.Variant({
    'pdf' : IDL.Null,
    'patreon' : IDL.Null,
    'linktree' : IDL.Null,
    'twitter' : IDL.Null,
    'other' : IDL.Null,
    'blog' : IDL.Null,
    'etsy' : IDL.Null,
    'instagram' : IDL.Null,
    'substack' : IDL.Null,
    'website' : IDL.Null,
    'shopify' : IDL.Null,
    'booking' : IDL.Null,
    'calendly' : IDL.Null,
    'donation' : IDL.Null,
    'store' : IDL.Null,
    'facebook' : IDL.Null,
    'gumroad' : IDL.Null,
    'events' : IDL.Null,
    'discord' : IDL.Null,
    'youtube' : IDL.Null,
    'signal' : IDL.Null,
    'newsletter' : IDL.Null,
    'telegram' : IDL.Null,
  });
  const ConnectedPresenceLink = IDL.Record({
    'url' : IDL.Text,
    'displayLabel' : IDL.Opt(IDL.Text),
    'linkType' : LinkType,
  });
  const MemberInput = IDL.Record({
    'region' : IDL.Opt(IDL.Text),
    'paymentQrImage' : IDL.Opt(IDL.Text),
    'latitude' : IDL.Opt(IDL.Float64),
    'contactName' : IDL.Text,
    'paymentInstructions' : IDL.Opt(IDL.Text),
    'province' : IDL.Text,
    'acceptsBitcoin' : IDL.Bool,
    'subcategory' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'postalCode' : IDL.Opt(IDL.Text),
    'socialLinks' : IDL.Opt(IDL.Text),
    'acceptsCash' : IDL.Bool,
    'acceptsFiat' : IDL.Bool,
    'participantType' : IDL.Text,
    'circularEconomyParticipant' : IDL.Bool,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'featuredContent' : IDL.Opt(FeaturedContent),
    'email' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'connectedPresence' : IDL.Opt(IDL.Vec(ConnectedPresenceLink)),
    'longitude' : IDL.Opt(IDL.Float64),
    'bitcoinAddress' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
    'oisyWalletLink' : IDL.Opt(IDL.Text),
    'acceptsICP' : IDL.Bool,
    'icpAddress' : IDL.Opt(IDL.Text),
  });
  const MemberParticipantType = IDL.Variant({
    'business' : IDL.Null,
    'organization' : IDL.Null,
    'individual' : IDL.Null,
    'producer' : IDL.Null,
  });
  const MembershipTier = IDL.Variant({
    'localProducer' : IDL.Null,
    'builderMember' : IDL.Null,
    'localSponsor' : IDL.Null,
    'verifiedBusiness' : IDL.Null,
    'communitySupporterTier' : IDL.Null,
    'communityPartner' : IDL.Null,
  });
  const MembershipIntentInput = IDL.Record({
    'principal' : IDL.Opt(IDL.Principal),
    'province' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'participantType' : MemberParticipantType,
    'email' : IDL.Text,
    'displayPublicly' : IDL.Bool,
    'message' : IDL.Opt(IDL.Text),
    'membershipTier' : MembershipTier,
  });
  const MembershipStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'contacted' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const MembershipIntent = IDL.Record({
    'id' : IDL.Text,
    'status' : MembershipStatus,
    'principal' : IDL.Opt(IDL.Principal),
    'province' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'participantType' : MemberParticipantType,
    'email' : IDL.Text,
    'displayPublicly' : IDL.Bool,
    'message' : IDL.Opt(IDL.Text),
    'membershipTier' : MembershipTier,
  });
  const Result__1 = IDL.Variant({ 'ok' : MembershipIntent, 'err' : IDL.Text });
  const OpportunityStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const OpportunityCategory = IDL.Variant({
    'creativeArts' : IDL.Null,
    'localFarming' : IDL.Null,
    'other' : IDL.Null,
    'education' : IDL.Null,
    'technology' : IDL.Null,
    'foodSupport' : IDL.Null,
    'events' : IDL.Null,
    'wellness' : IDL.Null,
    'cleanup' : IDL.Null,
    'delivery' : IDL.Null,
    'youthSupport' : IDL.Null,
    'mentorship' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const OpportunityInput = IDL.Record({
    'status' : OpportunityStatus,
    'memberId' : IDL.Opt(IDL.Text),
    'organizationName' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'contactLink' : IDL.Opt(IDL.Text),
    'province' : IDL.Text,
    'city' : IDL.Text,
    'recurring' : IDL.Bool,
    'trustScore' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'chapterId' : IDL.Opt(IDL.Text),
    'timeCommitment' : IDL.Opt(IDL.Text),
    'category' : OpportunityCategory,
  });
  const CommunityOpportunity = IDL.Record({
    'id' : IDL.Nat,
    'status' : OpportunityStatus,
    'memberId' : IDL.Opt(IDL.Text),
    'organizationName' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'contactLink' : IDL.Opt(IDL.Text),
    'province' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'recurring' : IDL.Bool,
    'trustScore' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'chapterId' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'timeCommitment' : IDL.Opt(IDL.Text),
    'category' : OpportunityCategory,
    'adminFlagged' : IDL.Opt(IDL.Bool),
  });
  const Result_4 = IDL.Variant({
    'ok' : CommunityOpportunity,
    'err' : IDL.Text,
  });
  const VolunteerInput = IDL.Record({
    'interests' : IDL.Vec(IDL.Text),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'availability' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const ActivityEvent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'province' : IDL.Text,
    'city' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'relatedListingId' : IDL.Opt(IDL.Text),
    'relatedChapterId' : IDL.Opt(IDL.Text),
    'eventType' : IDL.Text,
  });
  const ListingMembershipStatus = IDL.Variant({
    'supporter' : IDL.Null,
    'businessMember' : IDL.Null,
    'free' : IDL.Null,
    'sponsor' : IDL.Null,
    'producerMember' : IDL.Null,
    'partner' : IDL.Null,
  });
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const MemberRecord = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Opt(IDL.Text),
    'paymentQrImage' : IDL.Opt(IDL.Text),
    'latitude' : IDL.Opt(IDL.Float64),
    'votingFrozen' : IDL.Bool,
    'featured' : IDL.Bool,
    'communityVerified' : IDL.Bool,
    'contactName' : IDL.Text,
    'paymentInstructions' : IDL.Opt(IDL.Text),
    'province' : IDL.Text,
    'acceptsBitcoin' : IDL.Bool,
    'subcategory' : IDL.Opt(IDL.Text),
    'communityVerificationStatus' : IDL.Text,
    'city' : IDL.Text,
    'ownerPrincipal' : IDL.Opt(IDL.Text),
    'postalCode' : IDL.Opt(IDL.Text),
    'socialLinks' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'acceptsCash' : IDL.Bool,
    'acceptsFiat' : IDL.Bool,
    'participantType' : IDL.Text,
    'circularEconomyParticipant' : IDL.Bool,
    'businessName' : IDL.Text,
    'description' : IDL.Text,
    'featuredContent' : IDL.Opt(FeaturedContent),
    'email' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'membershipStatus' : ListingMembershipStatus,
    'updatedAt' : Timestamp,
    'connectedPresence' : IDL.Vec(ConnectedPresenceLink),
    'longitude' : IDL.Opt(IDL.Float64),
    'bitcoinAddress' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'flaggedForReview' : IDL.Bool,
    'communityDownvotes' : IDL.Nat,
    'phone' : IDL.Opt(IDL.Text),
    'oisyWalletLink' : IDL.Opt(IDL.Text),
    'acceptsICP' : IDL.Bool,
    'icpAddress' : IDL.Opt(IDL.Text),
    'verificationStatus' : VerificationStatus,
    'communityUpvotes' : IDL.Nat,
  });
  const AdminTrustQueue = IDL.Record({
    'highTrust' : IDL.Vec(MemberRecord),
    'pending' : IDL.Vec(MemberRecord),
    'flagged' : IDL.Vec(MemberRecord),
  });
  const Result_3 = IDL.Variant({ 'ok' : AdminTrustQueue, 'err' : IDL.Text });
  const CityStats = IDL.Record({
    'province' : IDL.Text,
    'producerCount' : IDL.Nat,
    'volunteerCount' : IDL.Nat,
    'businessCount' : IDL.Nat,
    'city' : IDL.Text,
    'memberCount' : IDL.Nat,
    'totalListings' : IDL.Nat,
  });
  const TrustSummary = IDL.Record({
    'upvotes' : IDL.Nat,
    'callerVote' : IDL.Opt(VoteType),
    'downvotes' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({ 'ok' : TrustSummary, 'err' : IDL.Text });
  const SearchFilters = IDL.Record({
    'province' : IDL.Opt(IDL.Text),
    'acceptsBitcoin' : IDL.Opt(IDL.Bool),
    'city' : IDL.Opt(IDL.Text),
    'circularEconomyParticipant' : IDL.Opt(IDL.Bool),
    'category' : IDL.Opt(IDL.Text),
    'acceptsICP' : IDL.Opt(IDL.Bool),
    'verificationStatus' : IDL.Opt(VerificationStatus),
  });
  const MembershipStats = IDL.Record({
    'byTier' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'total' : IDL.Nat,
    'estimatedMonthlySupport' : IDL.Nat,
    'byStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const StatsRecord = IDL.Record({
    'communityMembers' : IDL.Nat,
    'verifiedMembers' : IDL.Nat,
    'byProvince' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'circularEconomy' : IDL.Nat,
    'organizationPartners' : IDL.Nat,
    'bitcoinEnabled' : IDL.Nat,
    'producerMembers' : IDL.Nat,
    'pendingMembers' : IDL.Nat,
    'totalMembers' : IDL.Nat,
    'icpEnabled' : IDL.Nat,
    'businessMembers' : IDL.Nat,
    'tradeMembers' : IDL.Nat,
  });
  const VolunteerInterest = IDL.Record({
    'id' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'availability' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addCommunityVote' : IDL.Func([IDL.Text, VoteType], [Result_1], []),
    'adminFlagOpportunity' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
    'approveMember' : IDL.Func([IDL.Text], [Result], []),
    'createMember' : IDL.Func([MemberInput], [Result_1], []),
    'createMembershipIntent' : IDL.Func(
        [MembershipIntentInput],
        [Result__1],
        [],
      ),
    'createOpportunity' : IDL.Func([OpportunityInput], [Result_4], []),
    'createVolunteer' : IDL.Func([VolunteerInput], [Result_1], []),
    'deleteMember' : IDL.Func([IDL.Text], [Result], []),
    'featureMember' : IDL.Func([IDL.Text, IDL.Bool], [Result], []),
    'freezeVoting' : IDL.Func([IDL.Text, IDL.Bool], [Result_1], []),
    'getActivityFeed' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityEvent)],
        ['query'],
      ),
    'getAdminTrustQueue' : IDL.Func([], [Result_3], ['query']),
    'getCityStats' : IDL.Func([], [IDL.Vec(CityStats)], ['query']),
    'getCommunityVotes' : IDL.Func([IDL.Text], [Result_2], ['query']),
    'getLatestOpportunities' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CommunityOpportunity)],
        ['query'],
      ),
    'getLocalActivity' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(ActivityEvent)],
        ['query'],
      ),
    'getMember' : IDL.Func([IDL.Text], [IDL.Opt(MemberRecord)], ['query']),
    'getMembers' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(SearchFilters)],
        [IDL.Vec(MemberRecord)],
        ['query'],
      ),
    'getMembershipIntents' : IDL.Func(
        [],
        [IDL.Vec(MembershipIntent)],
        ['query'],
      ),
    'getMembershipIntentsByStatus' : IDL.Func(
        [MembershipStatus],
        [IDL.Vec(MembershipIntent)],
        ['query'],
      ),
    'getMembershipIntentsByTier' : IDL.Func(
        [MembershipTier],
        [IDL.Vec(MembershipIntent)],
        ['query'],
      ),
    'getMembershipStats' : IDL.Func([], [MembershipStats], ['query']),
    'getMyVote' : IDL.Func([IDL.Text], [IDL.Opt(VoteType)], ['query']),
    'getOpportunities' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(OpportunityCategory),
          IDL.Opt(OpportunityStatus),
        ],
        [IDL.Vec(CommunityOpportunity)],
        ['query'],
      ),
    'getOpportunitiesByMember' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CommunityOpportunity)],
        ['query'],
      ),
    'getOpportunityById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CommunityOpportunity)],
        ['query'],
      ),
    'getPublicSupporters' : IDL.Func(
        [],
        [IDL.Vec(MembershipIntent)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [StatsRecord], []),
    'getVolunteers' : IDL.Func([], [IDL.Vec(VolunteerInterest)], []),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'overrideTrustStatus' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'rejectMember' : IDL.Func([IDL.Text], [Result], []),
    'removeCommunityVote' : IDL.Func([IDL.Text], [Result_1], []),
    'updateMember' : IDL.Func([IDL.Text, MemberInput], [Result], []),
    'updateMembershipIntentStatus' : IDL.Func(
        [IDL.Text, MembershipStatus],
        [Result__1],
        [],
      ),
    'updateOpportunityStatus' : IDL.Func(
        [IDL.Nat, OpportunityStatus],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };