/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent {
  'id' : string,
  'title' : string,
  'province' : string,
  'city' : string,
  'description' : string,
  'timestamp' : bigint,
  'relatedListingId' : [] | [string],
  'relatedChapterId' : [] | [string],
  'eventType' : string,
}
export interface AdminTrustQueue {
  'highTrust' : Array<MemberRecord>,
  'pending' : Array<MemberRecord>,
  'flagged' : Array<MemberRecord>,
}
export interface CityStats {
  'province' : string,
  'producerCount' : bigint,
  'volunteerCount' : bigint,
  'businessCount' : bigint,
  'city' : string,
  'memberCount' : bigint,
  'totalListings' : bigint,
}
export interface CommunityOpportunity {
  'id' : bigint,
  'status' : OpportunityStatus,
  'memberId' : [] | [string],
  'organizationName' : [] | [string],
  'title' : string,
  'contactLink' : [] | [string],
  'province' : string,
  'city' : string,
  'createdAt' : bigint,
  'recurring' : boolean,
  'trustScore' : [] | [bigint],
  'description' : string,
  'chapterId' : [] | [string],
  'updatedAt' : bigint,
  'timeCommitment' : [] | [string],
  'category' : OpportunityCategory,
  'adminFlagged' : [] | [boolean],
}
export interface ConnectedPresenceLink {
  'url' : string,
  'displayLabel' : [] | [string],
  'linkType' : LinkType,
}
export interface FeaturedContent {
  'title' : string,
  'externalLink' : string,
  'featuredType' : [] | [string],
  'description' : string,
  'imageUrl' : [] | [string],
}
export type LinkType = { 'pdf' : null } |
  { 'patreon' : null } |
  { 'linktree' : null } |
  { 'twitter' : null } |
  { 'other' : null } |
  { 'blog' : null } |
  { 'etsy' : null } |
  { 'instagram' : null } |
  { 'substack' : null } |
  { 'website' : null } |
  { 'shopify' : null } |
  { 'booking' : null } |
  { 'calendly' : null } |
  { 'donation' : null } |
  { 'store' : null } |
  { 'facebook' : null } |
  { 'gumroad' : null } |
  { 'events' : null } |
  { 'discord' : null } |
  { 'youtube' : null } |
  { 'signal' : null } |
  { 'newsletter' : null } |
  { 'telegram' : null };
export type ListingMembershipStatus = { 'supporter' : null } |
  { 'businessMember' : null } |
  { 'free' : null } |
  { 'sponsor' : null } |
  { 'producerMember' : null } |
  { 'partner' : null };
export interface MemberInput {
  'region' : [] | [string],
  'paymentQrImage' : [] | [string],
  'latitude' : [] | [number],
  'contactName' : string,
  'paymentInstructions' : [] | [string],
  'province' : string,
  'acceptsBitcoin' : boolean,
  'subcategory' : [] | [string],
  'city' : string,
  'postalCode' : [] | [string],
  'socialLinks' : [] | [string],
  'acceptsCash' : boolean,
  'acceptsFiat' : boolean,
  'participantType' : string,
  'circularEconomyParticipant' : boolean,
  'businessName' : string,
  'description' : string,
  'featuredContent' : [] | [FeaturedContent],
  'email' : [] | [string],
  'website' : [] | [string],
  'connectedPresence' : [] | [Array<ConnectedPresenceLink>],
  'longitude' : [] | [number],
  'bitcoinAddress' : [] | [string],
  'category' : string,
  'phone' : [] | [string],
  'oisyWalletLink' : [] | [string],
  'acceptsICP' : boolean,
  'icpAddress' : [] | [string],
}
export type MemberParticipantType = { 'business' : null } |
  { 'organization' : null } |
  { 'individual' : null } |
  { 'producer' : null };
export interface MemberRecord {
  'id' : string,
  'region' : [] | [string],
  'paymentQrImage' : [] | [string],
  'latitude' : [] | [number],
  'votingFrozen' : boolean,
  'featured' : boolean,
  'communityVerified' : boolean,
  'contactName' : string,
  'paymentInstructions' : [] | [string],
  'province' : string,
  'acceptsBitcoin' : boolean,
  'subcategory' : [] | [string],
  'communityVerificationStatus' : string,
  'city' : string,
  'ownerPrincipal' : [] | [string],
  'postalCode' : [] | [string],
  'socialLinks' : [] | [string],
  'createdAt' : Timestamp,
  'acceptsCash' : boolean,
  'acceptsFiat' : boolean,
  'participantType' : string,
  'circularEconomyParticipant' : boolean,
  'businessName' : string,
  'description' : string,
  'featuredContent' : [] | [FeaturedContent],
  'email' : [] | [string],
  'website' : [] | [string],
  'membershipStatus' : ListingMembershipStatus,
  'updatedAt' : Timestamp,
  'connectedPresence' : Array<ConnectedPresenceLink>,
  'longitude' : [] | [number],
  'bitcoinAddress' : [] | [string],
  'category' : string,
  'flaggedForReview' : boolean,
  'communityDownvotes' : bigint,
  'phone' : [] | [string],
  'oisyWalletLink' : [] | [string],
  'acceptsICP' : boolean,
  'icpAddress' : [] | [string],
  'verificationStatus' : VerificationStatus,
  'communityUpvotes' : bigint,
}
export interface MembershipIntent {
  'id' : string,
  'status' : MembershipStatus,
  'principal' : [] | [Principal],
  'province' : string,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'participantType' : MemberParticipantType,
  'email' : string,
  'displayPublicly' : boolean,
  'message' : [] | [string],
  'membershipTier' : MembershipTier,
}
export interface MembershipIntentInput {
  'principal' : [] | [Principal],
  'province' : string,
  'city' : string,
  'name' : string,
  'participantType' : MemberParticipantType,
  'email' : string,
  'displayPublicly' : boolean,
  'message' : [] | [string],
  'membershipTier' : MembershipTier,
}
export interface MembershipStats {
  'byTier' : Array<[string, bigint]>,
  'total' : bigint,
  'estimatedMonthlySupport' : bigint,
  'byStatus' : Array<[string, bigint]>,
}
export type MembershipStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'contacted' : null };
export type MembershipTier = { 'localProducer' : null } |
  { 'builderMember' : null } |
  { 'localSponsor' : null } |
  { 'verifiedBusiness' : null } |
  { 'communitySupporterTier' : null } |
  { 'communityPartner' : null };
export type OpportunityCategory = { 'creativeArts' : null } |
  { 'localFarming' : null } |
  { 'other' : null } |
  { 'education' : null } |
  { 'technology' : null } |
  { 'foodSupport' : null } |
  { 'events' : null } |
  { 'wellness' : null } |
  { 'cleanup' : null } |
  { 'delivery' : null } |
  { 'youthSupport' : null } |
  { 'mentorship' : null } |
  { 'volunteer' : null };
export interface OpportunityInput {
  'status' : OpportunityStatus,
  'memberId' : [] | [string],
  'organizationName' : [] | [string],
  'title' : string,
  'contactLink' : [] | [string],
  'province' : string,
  'city' : string,
  'recurring' : boolean,
  'trustScore' : [] | [bigint],
  'description' : string,
  'chapterId' : [] | [string],
  'timeCommitment' : [] | [string],
  'category' : OpportunityCategory,
}
export type OpportunityStatus = { 'active' : null } |
  { 'inactive' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : string } |
  { 'err' : string };
export type Result_2 = { 'ok' : TrustSummary } |
  { 'err' : string };
export type Result_3 = { 'ok' : AdminTrustQueue } |
  { 'err' : string };
export type Result_4 = { 'ok' : CommunityOpportunity } |
  { 'err' : string };
export type Result__1 = { 'ok' : MembershipIntent } |
  { 'err' : string };
export interface SearchFilters {
  'province' : [] | [string],
  'acceptsBitcoin' : [] | [boolean],
  'city' : [] | [string],
  'circularEconomyParticipant' : [] | [boolean],
  'category' : [] | [string],
  'acceptsICP' : [] | [boolean],
  'verificationStatus' : [] | [VerificationStatus],
}
export interface StatsRecord {
  'communityMembers' : bigint,
  'verifiedMembers' : bigint,
  'byProvince' : Array<[string, bigint]>,
  'circularEconomy' : bigint,
  'organizationPartners' : bigint,
  'bitcoinEnabled' : bigint,
  'producerMembers' : bigint,
  'pendingMembers' : bigint,
  'totalMembers' : bigint,
  'icpEnabled' : bigint,
  'businessMembers' : bigint,
  'tradeMembers' : bigint,
}
export type Timestamp = bigint;
export interface TrustSummary {
  'upvotes' : bigint,
  'callerVote' : [] | [VoteType],
  'downvotes' : bigint,
}
export type VerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface VolunteerInput {
  'interests' : Array<string>,
  'city' : string,
  'name' : string,
  'email' : string,
  'availability' : string,
  'skills' : Array<string>,
}
export interface VolunteerInterest {
  'id' : string,
  'interests' : Array<string>,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'availability' : string,
  'skills' : Array<string>,
}
export type VoteType = { 'upvote' : null } |
  { 'downvote' : null };
export interface _SERVICE {
  'addCommunityVote' : ActorMethod<[string, VoteType], Result_1>,
  'adminFlagOpportunity' : ActorMethod<[bigint, boolean], Result>,
  'approveMember' : ActorMethod<[string], Result>,
  'createMember' : ActorMethod<[MemberInput], Result_1>,
  'createMembershipIntent' : ActorMethod<[MembershipIntentInput], Result__1>,
  'createOpportunity' : ActorMethod<[OpportunityInput], Result_4>,
  'createVolunteer' : ActorMethod<[VolunteerInput], Result_1>,
  'deleteMember' : ActorMethod<[string], Result>,
  'featureMember' : ActorMethod<[string, boolean], Result>,
  'freezeVoting' : ActorMethod<[string, boolean], Result_1>,
  'getActivityFeed' : ActorMethod<[bigint], Array<ActivityEvent>>,
  'getAdminTrustQueue' : ActorMethod<[], Result_3>,
  'getCityStats' : ActorMethod<[], Array<CityStats>>,
  'getCommunityVotes' : ActorMethod<[string], Result_2>,
  'getLatestOpportunities' : ActorMethod<[bigint], Array<CommunityOpportunity>>,
  'getLocalActivity' : ActorMethod<[string, bigint], Array<ActivityEvent>>,
  'getMember' : ActorMethod<[string], [] | [MemberRecord]>,
  'getMembers' : ActorMethod<
    [[] | [string], [] | [SearchFilters]],
    Array<MemberRecord>
  >,
  'getMembershipIntents' : ActorMethod<[], Array<MembershipIntent>>,
  'getMembershipIntentsByStatus' : ActorMethod<
    [MembershipStatus],
    Array<MembershipIntent>
  >,
  'getMembershipIntentsByTier' : ActorMethod<
    [MembershipTier],
    Array<MembershipIntent>
  >,
  'getMembershipStats' : ActorMethod<[], MembershipStats>,
  'getMyVote' : ActorMethod<[string], [] | [VoteType]>,
  'getOpportunities' : ActorMethod<
    [[] | [string], [] | [OpportunityCategory], [] | [OpportunityStatus]],
    Array<CommunityOpportunity>
  >,
  'getOpportunitiesByMember' : ActorMethod<
    [string],
    Array<CommunityOpportunity>
  >,
  'getOpportunityById' : ActorMethod<[bigint], [] | [CommunityOpportunity]>,
  'getPublicSupporters' : ActorMethod<[], Array<MembershipIntent>>,
  'getStats' : ActorMethod<[], StatsRecord>,
  'getVolunteers' : ActorMethod<[], Array<VolunteerInterest>>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'overrideTrustStatus' : ActorMethod<[string, string], Result_1>,
  'rejectMember' : ActorMethod<[string], Result>,
  'removeCommunityVote' : ActorMethod<[string], Result_1>,
  'updateMember' : ActorMethod<[string, MemberInput], Result>,
  'updateMembershipIntentStatus' : ActorMethod<
    [string, MembershipStatus],
    Result__1
  >,
  'updateOpportunityStatus' : ActorMethod<[bigint, OpportunityStatus], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];