/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MemberRecord {
    id: string;
    region?: string;
    paymentQrImage?: string;
    latitude?: number;
    votingFrozen: boolean;
    featured: boolean;
    communityVerified: boolean;
    contactName: string;
    paymentInstructions?: string;
    province: string;
    acceptsBitcoin: boolean;
    subcategory?: string;
    communityVerificationStatus: string;
    city: string;
    ownerPrincipal?: string;
    postalCode?: string;
    socialLinks?: string;
    createdAt: Timestamp;
    acceptsCash: boolean;
    acceptsFiat: boolean;
    participantType: string;
    circularEconomyParticipant: boolean;
    businessName: string;
    description: string;
    featuredContent?: FeaturedContent;
    email?: string;
    website?: string;
    membershipStatus: ListingMembershipStatus;
    updatedAt: Timestamp;
    connectedPresence: Array<ConnectedPresenceLink>;
    longitude?: number;
    bitcoinAddress?: string;
    category: string;
    flaggedForReview: boolean;
    communityDownvotes: bigint;
    phone?: string;
    oisyWalletLink?: string;
    acceptsICP: boolean;
    icpAddress?: string;
    verificationStatus: VerificationStatus;
    communityUpvotes: bigint;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: TrustSummary;
} | {
    __kind__: "err";
    err: string;
};
export interface ConnectedPresenceLink {
    url: string;
    displayLabel?: string;
    linkType: LinkType;
}
export interface CommunityOpportunity {
    id: bigint;
    status: OpportunityStatus;
    memberId?: string;
    organizationName?: string;
    title: string;
    contactLink?: string;
    province: string;
    city: string;
    createdAt: bigint;
    recurring: boolean;
    trustScore?: bigint;
    description: string;
    chapterId?: string;
    updatedAt: bigint;
    timeCommitment?: string;
    category: OpportunityCategory;
    adminFlagged?: boolean;
}
export interface VolunteerInput {
    interests: Array<string>;
    city: string;
    name: string;
    email: string;
    availability: string;
    skills: Array<string>;
}
export interface OpportunityInput {
    status: OpportunityStatus;
    memberId?: string;
    organizationName?: string;
    title: string;
    contactLink?: string;
    province: string;
    city: string;
    recurring: boolean;
    trustScore?: bigint;
    description: string;
    chapterId?: string;
    timeCommitment?: string;
    category: OpportunityCategory;
}
export type Result__1 = {
    __kind__: "ok";
    ok: MembershipIntent;
} | {
    __kind__: "err";
    err: string;
};
export interface CityStats {
    province: string;
    producerCount: bigint;
    volunteerCount: bigint;
    businessCount: bigint;
    city: string;
    memberCount: bigint;
    totalListings: bigint;
}
export interface AdminTrustQueue {
    highTrust: Array<MemberRecord>;
    pending: Array<MemberRecord>;
    flagged: Array<MemberRecord>;
}
export interface StatsRecord {
    communityMembers: bigint;
    verifiedMembers: bigint;
    byProvince: Array<[string, bigint]>;
    circularEconomy: bigint;
    organizationPartners: bigint;
    bitcoinEnabled: bigint;
    producerMembers: bigint;
    pendingMembers: bigint;
    totalMembers: bigint;
    icpEnabled: bigint;
    businessMembers: bigint;
    tradeMembers: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: CommunityOpportunity;
} | {
    __kind__: "err";
    err: string;
};
export interface ActivityEvent {
    id: string;
    title: string;
    province: string;
    city: string;
    description: string;
    timestamp: bigint;
    relatedListingId?: string;
    relatedChapterId?: string;
    eventType: string;
}
export interface TrustSummary {
    upvotes: bigint;
    callerVote?: VoteType;
    downvotes: bigint;
}
export interface SearchFilters {
    province?: string;
    acceptsBitcoin?: boolean;
    city?: string;
    circularEconomyParticipant?: boolean;
    category?: string;
    acceptsICP?: boolean;
    verificationStatus?: VerificationStatus;
}
export interface MembershipIntentInput {
    principal?: Principal;
    province: string;
    city: string;
    name: string;
    participantType: MemberParticipantType;
    email: string;
    displayPublicly: boolean;
    message?: string;
    membershipTier: MembershipTier;
}
export interface MemberInput {
    region?: string;
    paymentQrImage?: string;
    latitude?: number;
    contactName: string;
    paymentInstructions?: string;
    province: string;
    acceptsBitcoin: boolean;
    subcategory?: string;
    city: string;
    postalCode?: string;
    socialLinks?: string;
    acceptsCash: boolean;
    acceptsFiat: boolean;
    participantType: string;
    circularEconomyParticipant: boolean;
    businessName: string;
    description: string;
    featuredContent?: FeaturedContent;
    email?: string;
    website?: string;
    connectedPresence?: Array<ConnectedPresenceLink>;
    longitude?: number;
    bitcoinAddress?: string;
    category: string;
    phone?: string;
    oisyWalletLink?: string;
    acceptsICP: boolean;
    icpAddress?: string;
}
export interface FeaturedContent {
    title: string;
    externalLink: string;
    featuredType?: string;
    description: string;
    imageUrl?: string;
}
export interface VolunteerInterest {
    id: string;
    interests: Array<string>;
    city: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    availability: string;
    skills: Array<string>;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: AdminTrustQueue;
} | {
    __kind__: "err";
    err: string;
};
export interface MembershipStats {
    byTier: Array<[string, bigint]>;
    total: bigint;
    estimatedMonthlySupport: bigint;
    byStatus: Array<[string, bigint]>;
}
export interface MembershipIntent {
    id: string;
    status: MembershipStatus;
    principal?: Principal;
    province: string;
    city: string;
    name: string;
    createdAt: Timestamp;
    participantType: MemberParticipantType;
    email: string;
    displayPublicly: boolean;
    message?: string;
    membershipTier: MembershipTier;
}
export enum LinkType {
    pdf = "pdf",
    patreon = "patreon",
    linktree = "linktree",
    twitter = "twitter",
    other = "other",
    blog = "blog",
    etsy = "etsy",
    instagram = "instagram",
    substack = "substack",
    website = "website",
    shopify = "shopify",
    booking = "booking",
    calendly = "calendly",
    donation = "donation",
    store = "store",
    facebook = "facebook",
    gumroad = "gumroad",
    events = "events",
    discord = "discord",
    youtube = "youtube",
    signal = "signal",
    newsletter = "newsletter",
    telegram = "telegram"
}
export enum ListingMembershipStatus {
    supporter = "supporter",
    businessMember = "businessMember",
    free = "free",
    sponsor = "sponsor",
    producerMember = "producerMember",
    partner = "partner"
}
export enum MemberParticipantType {
    business = "business",
    organization = "organization",
    individual = "individual",
    producer = "producer"
}
export enum MembershipStatus {
    pending = "pending",
    approved = "approved",
    contacted = "contacted"
}
export enum MembershipTier {
    localProducer = "localProducer",
    builderMember = "builderMember",
    localSponsor = "localSponsor",
    verifiedBusiness = "verifiedBusiness",
    communitySupporterTier = "communitySupporterTier",
    communityPartner = "communityPartner"
}
export enum OpportunityCategory {
    creativeArts = "creativeArts",
    localFarming = "localFarming",
    other = "other",
    education = "education",
    technology = "technology",
    foodSupport = "foodSupport",
    events = "events",
    wellness = "wellness",
    cleanup = "cleanup",
    delivery = "delivery",
    youthSupport = "youthSupport",
    mentorship = "mentorship",
    volunteer = "volunteer"
}
export enum OpportunityStatus {
    active = "active",
    inactive = "inactive"
}
export enum VerificationStatus {
    verified = "verified",
    pending = "pending",
    rejected = "rejected"
}
export enum VoteType {
    upvote = "upvote",
    downvote = "downvote"
}
export interface backendInterface {
    addCommunityVote(listingId: string, voteType: VoteType): Promise<Result_1>;
    adminFlagOpportunity(id: bigint, flagged: boolean): Promise<Result>;
    approveMember(id: string): Promise<Result>;
    createMember(memberData: MemberInput): Promise<Result_1>;
    createMembershipIntent(input: MembershipIntentInput): Promise<Result__1>;
    createOpportunity(input: OpportunityInput): Promise<Result_4>;
    createVolunteer(volunteerData: VolunteerInput): Promise<Result_1>;
    deleteMember(id: string): Promise<Result>;
    featureMember(id: string, featured: boolean): Promise<Result>;
    freezeVoting(memberId: string, frozen: boolean): Promise<Result_1>;
    getActivityFeed(limit: bigint): Promise<Array<ActivityEvent>>;
    getAdminTrustQueue(): Promise<Result_3>;
    getCityStats(): Promise<Array<CityStats>>;
    getCommunityVotes(listingId: string): Promise<Result_2>;
    getLatestOpportunities(limit: bigint): Promise<Array<CommunityOpportunity>>;
    getLocalActivity(city: string, limit: bigint): Promise<Array<ActivityEvent>>;
    getMember(id: string): Promise<MemberRecord | null>;
    getMembers(searchQuery: string | null, filters: SearchFilters | null): Promise<Array<MemberRecord>>;
    getMembershipIntents(): Promise<Array<MembershipIntent>>;
    getMembershipIntentsByStatus(status: MembershipStatus): Promise<Array<MembershipIntent>>;
    getMembershipIntentsByTier(tier: MembershipTier): Promise<Array<MembershipIntent>>;
    getMembershipStats(): Promise<MembershipStats>;
    getMyVote(listingId: string): Promise<VoteType | null>;
    getOpportunities(city: string | null, category: OpportunityCategory | null, status: OpportunityStatus | null): Promise<Array<CommunityOpportunity>>;
    getOpportunitiesByMember(memberId: string): Promise<Array<CommunityOpportunity>>;
    getOpportunityById(id: bigint): Promise<CommunityOpportunity | null>;
    getPublicSupporters(): Promise<Array<MembershipIntent>>;
    getStats(): Promise<StatsRecord>;
    getVolunteers(): Promise<Array<VolunteerInterest>>;
    isAdmin(p: Principal): Promise<boolean>;
    overrideTrustStatus(memberId: string, newStatus: string): Promise<Result_1>;
    rejectMember(id: string): Promise<Result>;
    removeCommunityVote(listingId: string): Promise<Result_1>;
    updateMember(id: string, memberData: MemberInput): Promise<Result>;
    updateMembershipIntentStatus(id: string, newStatus: MembershipStatus): Promise<Result__1>;
    updateOpportunityStatus(id: bigint, status: OpportunityStatus): Promise<Result>;
}
import type { ActivityEvent as _ActivityEvent, AdminTrustQueue as _AdminTrustQueue, CommunityOpportunity as _CommunityOpportunity, ConnectedPresenceLink as _ConnectedPresenceLink, FeaturedContent as _FeaturedContent, LinkType as _LinkType, ListingMembershipStatus as _ListingMembershipStatus, MemberInput as _MemberInput, MemberParticipantType as _MemberParticipantType, MemberRecord as _MemberRecord, MembershipIntent as _MembershipIntent, MembershipIntentInput as _MembershipIntentInput, MembershipStatus as _MembershipStatus, MembershipTier as _MembershipTier, OpportunityCategory as _OpportunityCategory, OpportunityInput as _OpportunityInput, OpportunityStatus as _OpportunityStatus, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result__1 as _Result__1, SearchFilters as _SearchFilters, Timestamp as _Timestamp, TrustSummary as _TrustSummary, VerificationStatus as _VerificationStatus, VoteType as _VoteType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCommunityVote(arg0: string, arg1: VoteType): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommunityVote(arg0, to_candid_VoteType_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommunityVote(arg0, to_candid_VoteType_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminFlagOpportunity(arg0: bigint, arg1: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminFlagOpportunity(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminFlagOpportunity(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveMember(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMember(arg0);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMember(arg0);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMember(arg0: MemberInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createMember(to_candid_MemberInput_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMember(to_candid_MemberInput_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMembershipIntent(arg0: MembershipIntentInput): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.createMembershipIntent(to_candid_MembershipIntentInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result__1_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMembershipIntent(to_candid_MembershipIntentInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result__1_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOpportunity(arg0: OpportunityInput): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.createOpportunity(to_candid_OpportunityInput_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_4_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOpportunity(to_candid_OpportunityInput_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_4_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVolunteer(arg0: VolunteerInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createVolunteer(arg0);
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVolunteer(arg0);
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMember(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async featureMember(arg0: string, arg1: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.featureMember(arg0, arg1);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.featureMember(arg0, arg1);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async freezeVoting(arg0: string, arg1: boolean): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.freezeVoting(arg0, arg1);
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.freezeVoting(arg0, arg1);
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityFeed(arg0: bigint): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityFeed(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityFeed(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminTrustQueue(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminTrustQueue();
                return from_candid_Result_3_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminTrustQueue();
            return from_candid_Result_3_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCityStats(): Promise<Array<CityStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCityStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCityStats();
            return result;
        }
    }
    async getCommunityVotes(arg0: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityVotes(arg0);
                return from_candid_Result_2_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityVotes(arg0);
            return from_candid_Result_2_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestOpportunities(arg0: bigint): Promise<Array<CommunityOpportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestOpportunities(arg0);
                return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestOpportunities(arg0);
            return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocalActivity(arg0: string, arg1: bigint): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocalActivity(arg0, arg1);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocalActivity(arg0, arg1);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: string): Promise<MemberRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembers(arg0: string | null, arg1: SearchFilters | null): Promise<Array<MemberRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembers(to_candid_opt_n82(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n83(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembers(to_candid_opt_n82(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n83(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipIntents(): Promise<Array<MembershipIntent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipIntents();
                return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipIntents();
            return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipIntentsByStatus(arg0: MembershipStatus): Promise<Array<MembershipIntent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipIntentsByStatus(to_candid_MembershipStatus_n89(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipIntentsByStatus(to_candid_MembershipStatus_n89(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipIntentsByTier(arg0: MembershipTier): Promise<Array<MembershipIntent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipIntentsByTier(to_candid_MembershipTier_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipIntentsByTier(to_candid_MembershipTier_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMembershipStats(): Promise<MembershipStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipStats();
            return result;
        }
    }
    async getMyVote(arg0: string): Promise<VoteType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVote(arg0);
                return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVote(arg0);
            return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunities(arg0: string | null, arg1: OpportunityCategory | null, arg2: OpportunityStatus | null): Promise<Array<CommunityOpportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunities(to_candid_opt_n82(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n91(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunities(to_candid_opt_n82(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n91(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunitiesByMember(arg0: string): Promise<Array<CommunityOpportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunitiesByMember(arg0);
                return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunitiesByMember(arg0);
            return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunityById(arg0: bigint): Promise<CommunityOpportunity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunityById(arg0);
                return from_candid_opt_n93(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunityById(arg0);
            return from_candid_opt_n93(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicSupporters(): Promise<Array<MembershipIntent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicSupporters();
                return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicSupporters();
            return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<StatsRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getVolunteers(): Promise<Array<VolunteerInterest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteers();
            return result;
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async overrideTrustStatus(arg0: string, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.overrideTrustStatus(arg0, arg1);
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.overrideTrustStatus(arg0, arg1);
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectMember(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectMember(arg0);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectMember(arg0);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeCommunityVote(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCommunityVote(arg0);
                return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCommunityVote(arg0);
            return from_candid_Result_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMember(arg0: string, arg1: MemberInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(arg0, to_candid_MemberInput_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(arg0, to_candid_MemberInput_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMembershipIntentStatus(arg0: string, arg1: MembershipStatus): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipIntentStatus(arg0, to_candid_MembershipStatus_n89(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result__1_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipIntentStatus(arg0, to_candid_MembershipStatus_n89(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result__1_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOpportunityStatus(arg0: bigint, arg1: OpportunityStatus): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOpportunityStatus(arg0, to_candid_OpportunityStatus_n36(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOpportunityStatus(arg0, to_candid_OpportunityStatus_n36(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityEvent_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEvent): ActivityEvent {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_AdminTrustQueue_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminTrustQueue): AdminTrustQueue {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_CommunityOpportunity_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityOpportunity): CommunityOpportunity {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_ConnectedPresenceLink_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectedPresenceLink): ConnectedPresenceLink {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_FeaturedContent_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeaturedContent): FeaturedContent {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_LinkType_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LinkType): LinkType {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_ListingMembershipStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingMembershipStatus): ListingMembershipStatus {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_MemberParticipantType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberParticipantType): MemberParticipantType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_MemberRecord_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberRecord): MemberRecord {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipIntent_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipIntent): MembershipIntent {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipStatus): MembershipStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipTier_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipTier): MembershipTier {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_OpportunityCategory_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OpportunityCategory): OpportunityCategory {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_OpportunityStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OpportunityStatus): OpportunityStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TrustSummary_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrustSummary): TrustSummary {
    return from_candid_record_n76(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function from_candid_VoteType_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoteType): VoteType {
    return from_candid_variant_n79(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FeaturedContent]): FeaturedContent | null {
    return value.length === 0 ? null : from_candid_FeaturedContent_n62(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoteType]): VoteType | null {
    return value.length === 0 ? null : from_candid_VoteType_n78(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberRecord]): MemberRecord | null {
    return value.length === 0 ? null : from_candid_MemberRecord_n58(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommunityOpportunity]): CommunityOpportunity | null {
    return value.length === 0 ? null : from_candid_CommunityOpportunity_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _MembershipStatus;
    principal: [] | [Principal];
    province: string;
    city: string;
    name: string;
    createdAt: _Timestamp;
    participantType: _MemberParticipantType;
    email: string;
    displayPublicly: boolean;
    message: [] | [string];
    membershipTier: _MembershipTier;
}): {
    id: string;
    status: MembershipStatus;
    principal?: Principal;
    province: string;
    city: string;
    name: string;
    createdAt: Timestamp;
    participantType: MemberParticipantType;
    email: string;
    displayPublicly: boolean;
    message?: string;
    membershipTier: MembershipTier;
} {
    return {
        id: value.id,
        status: from_candid_MembershipStatus_n26(_uploadFile, _downloadFile, value.status),
        principal: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.principal)),
        province: value.province,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        participantType: from_candid_MemberParticipantType_n29(_uploadFile, _downloadFile, value.participantType),
        email: value.email,
        displayPublicly: value.displayPublicly,
        message: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.message)),
        membershipTier: from_candid_MembershipTier_n32(_uploadFile, _downloadFile, value.membershipTier)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OpportunityStatus;
    memberId: [] | [string];
    organizationName: [] | [string];
    title: string;
    contactLink: [] | [string];
    province: string;
    city: string;
    createdAt: bigint;
    recurring: boolean;
    trustScore: [] | [bigint];
    description: string;
    chapterId: [] | [string];
    updatedAt: bigint;
    timeCommitment: [] | [string];
    category: _OpportunityCategory;
    adminFlagged: [] | [boolean];
}): {
    id: bigint;
    status: OpportunityStatus;
    memberId?: string;
    organizationName?: string;
    title: string;
    contactLink?: string;
    province: string;
    city: string;
    createdAt: bigint;
    recurring: boolean;
    trustScore?: bigint;
    description: string;
    chapterId?: string;
    updatedAt: bigint;
    timeCommitment?: string;
    category: OpportunityCategory;
    adminFlagged?: boolean;
} {
    return {
        id: value.id,
        status: from_candid_OpportunityStatus_n44(_uploadFile, _downloadFile, value.status),
        memberId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.memberId)),
        organizationName: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.organizationName)),
        title: value.title,
        contactLink: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.contactLink)),
        province: value.province,
        city: value.city,
        createdAt: value.createdAt,
        recurring: value.recurring,
        trustScore: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.trustScore)),
        description: value.description,
        chapterId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.chapterId)),
        updatedAt: value.updatedAt,
        timeCommitment: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.timeCommitment)),
        category: from_candid_OpportunityCategory_n47(_uploadFile, _downloadFile, value.category),
        adminFlagged: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.adminFlagged))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    province: string;
    city: string;
    description: string;
    timestamp: bigint;
    relatedListingId: [] | [string];
    relatedChapterId: [] | [string];
    eventType: string;
}): {
    id: string;
    title: string;
    province: string;
    city: string;
    description: string;
    timestamp: bigint;
    relatedListingId?: string;
    relatedChapterId?: string;
    eventType: string;
} {
    return {
        id: value.id,
        title: value.title,
        province: value.province,
        city: value.city,
        description: value.description,
        timestamp: value.timestamp,
        relatedListingId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.relatedListingId)),
        relatedChapterId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.relatedChapterId)),
        eventType: value.eventType
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    highTrust: Array<_MemberRecord>;
    pending: Array<_MemberRecord>;
    flagged: Array<_MemberRecord>;
}): {
    highTrust: Array<MemberRecord>;
    pending: Array<MemberRecord>;
    flagged: Array<MemberRecord>;
} {
    return {
        highTrust: from_candid_vec_n57(_uploadFile, _downloadFile, value.highTrust),
        pending: from_candid_vec_n57(_uploadFile, _downloadFile, value.pending),
        flagged: from_candid_vec_n57(_uploadFile, _downloadFile, value.flagged)
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    region: [] | [string];
    paymentQrImage: [] | [string];
    latitude: [] | [number];
    votingFrozen: boolean;
    featured: boolean;
    communityVerified: boolean;
    contactName: string;
    paymentInstructions: [] | [string];
    province: string;
    acceptsBitcoin: boolean;
    subcategory: [] | [string];
    communityVerificationStatus: string;
    city: string;
    ownerPrincipal: [] | [string];
    postalCode: [] | [string];
    socialLinks: [] | [string];
    createdAt: _Timestamp;
    acceptsCash: boolean;
    acceptsFiat: boolean;
    participantType: string;
    circularEconomyParticipant: boolean;
    businessName: string;
    description: string;
    featuredContent: [] | [_FeaturedContent];
    email: [] | [string];
    website: [] | [string];
    membershipStatus: _ListingMembershipStatus;
    updatedAt: _Timestamp;
    connectedPresence: Array<_ConnectedPresenceLink>;
    longitude: [] | [number];
    bitcoinAddress: [] | [string];
    category: string;
    flaggedForReview: boolean;
    communityDownvotes: bigint;
    phone: [] | [string];
    oisyWalletLink: [] | [string];
    acceptsICP: boolean;
    icpAddress: [] | [string];
    verificationStatus: _VerificationStatus;
    communityUpvotes: bigint;
}): {
    id: string;
    region?: string;
    paymentQrImage?: string;
    latitude?: number;
    votingFrozen: boolean;
    featured: boolean;
    communityVerified: boolean;
    contactName: string;
    paymentInstructions?: string;
    province: string;
    acceptsBitcoin: boolean;
    subcategory?: string;
    communityVerificationStatus: string;
    city: string;
    ownerPrincipal?: string;
    postalCode?: string;
    socialLinks?: string;
    createdAt: Timestamp;
    acceptsCash: boolean;
    acceptsFiat: boolean;
    participantType: string;
    circularEconomyParticipant: boolean;
    businessName: string;
    description: string;
    featuredContent?: FeaturedContent;
    email?: string;
    website?: string;
    membershipStatus: ListingMembershipStatus;
    updatedAt: Timestamp;
    connectedPresence: Array<ConnectedPresenceLink>;
    longitude?: number;
    bitcoinAddress?: string;
    category: string;
    flaggedForReview: boolean;
    communityDownvotes: bigint;
    phone?: string;
    oisyWalletLink?: string;
    acceptsICP: boolean;
    icpAddress?: string;
    verificationStatus: VerificationStatus;
    communityUpvotes: bigint;
} {
    return {
        id: value.id,
        region: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.region)),
        paymentQrImage: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.paymentQrImage)),
        latitude: record_opt_to_undefined(from_candid_opt_n60(_uploadFile, _downloadFile, value.latitude)),
        votingFrozen: value.votingFrozen,
        featured: value.featured,
        communityVerified: value.communityVerified,
        contactName: value.contactName,
        paymentInstructions: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.paymentInstructions)),
        province: value.province,
        acceptsBitcoin: value.acceptsBitcoin,
        subcategory: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.subcategory)),
        communityVerificationStatus: value.communityVerificationStatus,
        city: value.city,
        ownerPrincipal: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.ownerPrincipal)),
        postalCode: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.postalCode)),
        socialLinks: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.socialLinks)),
        createdAt: value.createdAt,
        acceptsCash: value.acceptsCash,
        acceptsFiat: value.acceptsFiat,
        participantType: value.participantType,
        circularEconomyParticipant: value.circularEconomyParticipant,
        businessName: value.businessName,
        description: value.description,
        featuredContent: record_opt_to_undefined(from_candid_opt_n61(_uploadFile, _downloadFile, value.featuredContent)),
        email: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.email)),
        website: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.website)),
        membershipStatus: from_candid_ListingMembershipStatus_n64(_uploadFile, _downloadFile, value.membershipStatus),
        updatedAt: value.updatedAt,
        connectedPresence: from_candid_vec_n66(_uploadFile, _downloadFile, value.connectedPresence),
        longitude: record_opt_to_undefined(from_candid_opt_n60(_uploadFile, _downloadFile, value.longitude)),
        bitcoinAddress: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.bitcoinAddress)),
        category: value.category,
        flaggedForReview: value.flaggedForReview,
        communityDownvotes: value.communityDownvotes,
        phone: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.phone)),
        oisyWalletLink: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.oisyWalletLink)),
        acceptsICP: value.acceptsICP,
        icpAddress: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.icpAddress)),
        verificationStatus: from_candid_VerificationStatus_n71(_uploadFile, _downloadFile, value.verificationStatus),
        communityUpvotes: value.communityUpvotes
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    externalLink: string;
    featuredType: [] | [string];
    description: string;
    imageUrl: [] | [string];
}): {
    title: string;
    externalLink: string;
    featuredType?: string;
    description: string;
    imageUrl?: string;
} {
    return {
        title: value.title,
        externalLink: value.externalLink,
        featuredType: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.featuredType)),
        description: value.description,
        imageUrl: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.imageUrl))
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    displayLabel: [] | [string];
    linkType: _LinkType;
}): {
    url: string;
    displayLabel?: string;
    linkType: LinkType;
} {
    return {
        url: value.url,
        displayLabel: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.displayLabel)),
        linkType: from_candid_LinkType_n69(_uploadFile, _downloadFile, value.linkType)
    };
}
function from_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upvotes: bigint;
    callerVote: [] | [_VoteType];
    downvotes: bigint;
}): {
    upvotes: bigint;
    callerVote?: VoteType;
    downvotes: bigint;
} {
    return {
        upvotes: value.upvotes,
        callerVote: record_opt_to_undefined(from_candid_opt_n77(_uploadFile, _downloadFile, value.callerVote)),
        downvotes: value.downvotes
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MembershipIntent;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MembershipIntent;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_MembershipIntent_n24(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    contacted: null;
}): MembershipStatus {
    return "pending" in value ? MembershipStatus.pending : "approved" in value ? MembershipStatus.approved : "contacted" in value ? MembershipStatus.contacted : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    business: null;
} | {
    organization: null;
} | {
    individual: null;
} | {
    producer: null;
}): MemberParticipantType {
    return "business" in value ? MemberParticipantType.business : "organization" in value ? MemberParticipantType.organization : "individual" in value ? MemberParticipantType.individual : "producer" in value ? MemberParticipantType.producer : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    localProducer: null;
} | {
    builderMember: null;
} | {
    localSponsor: null;
} | {
    verifiedBusiness: null;
} | {
    communitySupporterTier: null;
} | {
    communityPartner: null;
}): MembershipTier {
    return "localProducer" in value ? MembershipTier.localProducer : "builderMember" in value ? MembershipTier.builderMember : "localSponsor" in value ? MembershipTier.localSponsor : "verifiedBusiness" in value ? MembershipTier.verifiedBusiness : "communitySupporterTier" in value ? MembershipTier.communitySupporterTier : "communityPartner" in value ? MembershipTier.communityPartner : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CommunityOpportunity;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CommunityOpportunity;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CommunityOpportunity_n42(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): OpportunityStatus {
    return "active" in value ? OpportunityStatus.active : "inactive" in value ? OpportunityStatus.inactive : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creativeArts: null;
} | {
    localFarming: null;
} | {
    other: null;
} | {
    education: null;
} | {
    technology: null;
} | {
    foodSupport: null;
} | {
    events: null;
} | {
    wellness: null;
} | {
    cleanup: null;
} | {
    delivery: null;
} | {
    youthSupport: null;
} | {
    mentorship: null;
} | {
    volunteer: null;
}): OpportunityCategory {
    return "creativeArts" in value ? OpportunityCategory.creativeArts : "localFarming" in value ? OpportunityCategory.localFarming : "other" in value ? OpportunityCategory.other : "education" in value ? OpportunityCategory.education : "technology" in value ? OpportunityCategory.technology : "foodSupport" in value ? OpportunityCategory.foodSupport : "events" in value ? OpportunityCategory.events : "wellness" in value ? OpportunityCategory.wellness : "cleanup" in value ? OpportunityCategory.cleanup : "delivery" in value ? OpportunityCategory.delivery : "youthSupport" in value ? OpportunityCategory.youthSupport : "mentorship" in value ? OpportunityCategory.mentorship : "volunteer" in value ? OpportunityCategory.volunteer : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AdminTrustQueue;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AdminTrustQueue;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AdminTrustQueue_n55(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supporter: null;
} | {
    businessMember: null;
} | {
    free: null;
} | {
    sponsor: null;
} | {
    producerMember: null;
} | {
    partner: null;
}): ListingMembershipStatus {
    return "supporter" in value ? ListingMembershipStatus.supporter : "businessMember" in value ? ListingMembershipStatus.businessMember : "free" in value ? ListingMembershipStatus.free : "sponsor" in value ? ListingMembershipStatus.sponsor : "producerMember" in value ? ListingMembershipStatus.producerMember : "partner" in value ? ListingMembershipStatus.partner : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    patreon: null;
} | {
    linktree: null;
} | {
    twitter: null;
} | {
    other: null;
} | {
    blog: null;
} | {
    etsy: null;
} | {
    instagram: null;
} | {
    substack: null;
} | {
    website: null;
} | {
    shopify: null;
} | {
    booking: null;
} | {
    calendly: null;
} | {
    donation: null;
} | {
    store: null;
} | {
    facebook: null;
} | {
    gumroad: null;
} | {
    events: null;
} | {
    discord: null;
} | {
    youtube: null;
} | {
    signal: null;
} | {
    newsletter: null;
} | {
    telegram: null;
}): LinkType {
    return "pdf" in value ? LinkType.pdf : "patreon" in value ? LinkType.patreon : "linktree" in value ? LinkType.linktree : "twitter" in value ? LinkType.twitter : "other" in value ? LinkType.other : "blog" in value ? LinkType.blog : "etsy" in value ? LinkType.etsy : "instagram" in value ? LinkType.instagram : "substack" in value ? LinkType.substack : "website" in value ? LinkType.website : "shopify" in value ? LinkType.shopify : "booking" in value ? LinkType.booking : "calendly" in value ? LinkType.calendly : "donation" in value ? LinkType.donation : "store" in value ? LinkType.store : "facebook" in value ? LinkType.facebook : "gumroad" in value ? LinkType.gumroad : "events" in value ? LinkType.events : "discord" in value ? LinkType.discord : "youtube" in value ? LinkType.youtube : "signal" in value ? LinkType.signal : "newsletter" in value ? LinkType.newsletter : "telegram" in value ? LinkType.telegram : value;
}
function from_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
}): VerificationStatus {
    return "verified" in value ? VerificationStatus.verified : "pending" in value ? VerificationStatus.pending : "rejected" in value ? VerificationStatus.rejected : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TrustSummary;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TrustSummary;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TrustSummary_n75(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upvote: null;
} | {
    downvote: null;
}): VoteType {
    return "upvote" in value ? VoteType.upvote : "downvote" in value ? VoteType.downvote : value;
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEvent>): Array<ActivityEvent> {
    return value.map((x)=>from_candid_ActivityEvent_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberRecord>): Array<MemberRecord> {
    return value.map((x)=>from_candid_MemberRecord_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConnectedPresenceLink>): Array<ConnectedPresenceLink> {
    return value.map((x)=>from_candid_ConnectedPresenceLink_n67(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommunityOpportunity>): Array<CommunityOpportunity> {
    return value.map((x)=>from_candid_CommunityOpportunity_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MembershipIntent>): Array<MembershipIntent> {
    return value.map((x)=>from_candid_MembershipIntent_n24(_uploadFile, _downloadFile, x));
}
function to_candid_ConnectedPresenceLink_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConnectedPresenceLink): _ConnectedPresenceLink {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_FeaturedContent_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeaturedContent): _FeaturedContent {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_LinkType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LinkType): _LinkType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_MemberInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberInput): _MemberInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_MemberParticipantType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberParticipantType): _MemberParticipantType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipIntentInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipIntentInput): _MembershipIntentInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipStatus_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipStatus): _MembershipStatus {
    return to_candid_variant_n90(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipTier_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): _MembershipTier {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_OpportunityCategory_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityCategory): _OpportunityCategory {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_OpportunityInput_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityInput): _OpportunityInput {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_OpportunityStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityStatus): _OpportunityStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SearchFilters_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilters): _SearchFilters {
    return to_candid_record_n85(_uploadFile, _downloadFile, value);
}
function to_candid_VerificationStatus_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): _VerificationStatus {
    return to_candid_variant_n87(_uploadFile, _downloadFile, value);
}
function to_candid_VoteType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoteType): _VoteType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilters | null): [] | [_SearchFilters] {
    return value === null ? candid_none() : candid_some(to_candid_SearchFilters_n84(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityCategory | null): [] | [_OpportunityCategory] {
    return value === null ? candid_none() : candid_some(to_candid_OpportunityCategory_n38(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityStatus | null): [] | [_OpportunityStatus] {
    return value === null ? candid_none() : candid_some(to_candid_OpportunityStatus_n36(_uploadFile, _downloadFile, value));
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    externalLink: string;
    featuredType?: string;
    description: string;
    imageUrl?: string;
}): {
    title: string;
    externalLink: string;
    featuredType: [] | [string];
    description: string;
    imageUrl: [] | [string];
} {
    return {
        title: value.title,
        externalLink: value.externalLink,
        featuredType: value.featuredType ? candid_some(value.featuredType) : candid_none(),
        description: value.description,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none()
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    displayLabel?: string;
    linkType: LinkType;
}): {
    url: string;
    displayLabel: [] | [string];
    linkType: _LinkType;
} {
    return {
        url: value.url,
        displayLabel: value.displayLabel ? candid_some(value.displayLabel) : candid_none(),
        linkType: to_candid_LinkType_n14(_uploadFile, _downloadFile, value.linkType)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal?: Principal;
    province: string;
    city: string;
    name: string;
    participantType: MemberParticipantType;
    email: string;
    displayPublicly: boolean;
    message?: string;
    membershipTier: MembershipTier;
}): {
    principal: [] | [Principal];
    province: string;
    city: string;
    name: string;
    participantType: _MemberParticipantType;
    email: string;
    displayPublicly: boolean;
    message: [] | [string];
    membershipTier: _MembershipTier;
} {
    return {
        principal: value.principal ? candid_some(value.principal) : candid_none(),
        province: value.province,
        city: value.city,
        name: value.name,
        participantType: to_candid_MemberParticipantType_n18(_uploadFile, _downloadFile, value.participantType),
        email: value.email,
        displayPublicly: value.displayPublicly,
        message: value.message ? candid_some(value.message) : candid_none(),
        membershipTier: to_candid_MembershipTier_n20(_uploadFile, _downloadFile, value.membershipTier)
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: OpportunityStatus;
    memberId?: string;
    organizationName?: string;
    title: string;
    contactLink?: string;
    province: string;
    city: string;
    recurring: boolean;
    trustScore?: bigint;
    description: string;
    chapterId?: string;
    timeCommitment?: string;
    category: OpportunityCategory;
}): {
    status: _OpportunityStatus;
    memberId: [] | [string];
    organizationName: [] | [string];
    title: string;
    contactLink: [] | [string];
    province: string;
    city: string;
    recurring: boolean;
    trustScore: [] | [bigint];
    description: string;
    chapterId: [] | [string];
    timeCommitment: [] | [string];
    category: _OpportunityCategory;
} {
    return {
        status: to_candid_OpportunityStatus_n36(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId ? candid_some(value.memberId) : candid_none(),
        organizationName: value.organizationName ? candid_some(value.organizationName) : candid_none(),
        title: value.title,
        contactLink: value.contactLink ? candid_some(value.contactLink) : candid_none(),
        province: value.province,
        city: value.city,
        recurring: value.recurring,
        trustScore: value.trustScore ? candid_some(value.trustScore) : candid_none(),
        description: value.description,
        chapterId: value.chapterId ? candid_some(value.chapterId) : candid_none(),
        timeCommitment: value.timeCommitment ? candid_some(value.timeCommitment) : candid_none(),
        category: to_candid_OpportunityCategory_n38(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region?: string;
    paymentQrImage?: string;
    latitude?: number;
    contactName: string;
    paymentInstructions?: string;
    province: string;
    acceptsBitcoin: boolean;
    subcategory?: string;
    city: string;
    postalCode?: string;
    socialLinks?: string;
    acceptsCash: boolean;
    acceptsFiat: boolean;
    participantType: string;
    circularEconomyParticipant: boolean;
    businessName: string;
    description: string;
    featuredContent?: FeaturedContent;
    email?: string;
    website?: string;
    connectedPresence?: Array<ConnectedPresenceLink>;
    longitude?: number;
    bitcoinAddress?: string;
    category: string;
    phone?: string;
    oisyWalletLink?: string;
    acceptsICP: boolean;
    icpAddress?: string;
}): {
    region: [] | [string];
    paymentQrImage: [] | [string];
    latitude: [] | [number];
    contactName: string;
    paymentInstructions: [] | [string];
    province: string;
    acceptsBitcoin: boolean;
    subcategory: [] | [string];
    city: string;
    postalCode: [] | [string];
    socialLinks: [] | [string];
    acceptsCash: boolean;
    acceptsFiat: boolean;
    participantType: string;
    circularEconomyParticipant: boolean;
    businessName: string;
    description: string;
    featuredContent: [] | [_FeaturedContent];
    email: [] | [string];
    website: [] | [string];
    connectedPresence: [] | [Array<_ConnectedPresenceLink>];
    longitude: [] | [number];
    bitcoinAddress: [] | [string];
    category: string;
    phone: [] | [string];
    oisyWalletLink: [] | [string];
    acceptsICP: boolean;
    icpAddress: [] | [string];
} {
    return {
        region: value.region ? candid_some(value.region) : candid_none(),
        paymentQrImage: value.paymentQrImage ? candid_some(value.paymentQrImage) : candid_none(),
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        contactName: value.contactName,
        paymentInstructions: value.paymentInstructions ? candid_some(value.paymentInstructions) : candid_none(),
        province: value.province,
        acceptsBitcoin: value.acceptsBitcoin,
        subcategory: value.subcategory ? candid_some(value.subcategory) : candid_none(),
        city: value.city,
        postalCode: value.postalCode ? candid_some(value.postalCode) : candid_none(),
        socialLinks: value.socialLinks ? candid_some(value.socialLinks) : candid_none(),
        acceptsCash: value.acceptsCash,
        acceptsFiat: value.acceptsFiat,
        participantType: value.participantType,
        circularEconomyParticipant: value.circularEconomyParticipant,
        businessName: value.businessName,
        description: value.description,
        featuredContent: value.featuredContent ? candid_some(to_candid_FeaturedContent_n9(_uploadFile, _downloadFile, value.featuredContent)) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        website: value.website ? candid_some(value.website) : candid_none(),
        connectedPresence: value.connectedPresence ? candid_some(to_candid_vec_n11(_uploadFile, _downloadFile, value.connectedPresence)) : candid_none(),
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        bitcoinAddress: value.bitcoinAddress ? candid_some(value.bitcoinAddress) : candid_none(),
        category: value.category,
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        oisyWalletLink: value.oisyWalletLink ? candid_some(value.oisyWalletLink) : candid_none(),
        acceptsICP: value.acceptsICP,
        icpAddress: value.icpAddress ? candid_some(value.icpAddress) : candid_none()
    };
}
function to_candid_record_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    province?: string;
    acceptsBitcoin?: boolean;
    city?: string;
    circularEconomyParticipant?: boolean;
    category?: string;
    acceptsICP?: boolean;
    verificationStatus?: VerificationStatus;
}): {
    province: [] | [string];
    acceptsBitcoin: [] | [boolean];
    city: [] | [string];
    circularEconomyParticipant: [] | [boolean];
    category: [] | [string];
    acceptsICP: [] | [boolean];
    verificationStatus: [] | [_VerificationStatus];
} {
    return {
        province: value.province ? candid_some(value.province) : candid_none(),
        acceptsBitcoin: value.acceptsBitcoin ? candid_some(value.acceptsBitcoin) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        circularEconomyParticipant: value.circularEconomyParticipant ? candid_some(value.circularEconomyParticipant) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        acceptsICP: value.acceptsICP ? candid_some(value.acceptsICP) : candid_none(),
        verificationStatus: value.verificationStatus ? candid_some(to_candid_VerificationStatus_n86(_uploadFile, _downloadFile, value.verificationStatus)) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LinkType): {
    pdf: null;
} | {
    patreon: null;
} | {
    linktree: null;
} | {
    twitter: null;
} | {
    other: null;
} | {
    blog: null;
} | {
    etsy: null;
} | {
    instagram: null;
} | {
    substack: null;
} | {
    website: null;
} | {
    shopify: null;
} | {
    booking: null;
} | {
    calendly: null;
} | {
    donation: null;
} | {
    store: null;
} | {
    facebook: null;
} | {
    gumroad: null;
} | {
    events: null;
} | {
    discord: null;
} | {
    youtube: null;
} | {
    signal: null;
} | {
    newsletter: null;
} | {
    telegram: null;
} {
    return value == LinkType.pdf ? {
        pdf: null
    } : value == LinkType.patreon ? {
        patreon: null
    } : value == LinkType.linktree ? {
        linktree: null
    } : value == LinkType.twitter ? {
        twitter: null
    } : value == LinkType.other ? {
        other: null
    } : value == LinkType.blog ? {
        blog: null
    } : value == LinkType.etsy ? {
        etsy: null
    } : value == LinkType.instagram ? {
        instagram: null
    } : value == LinkType.substack ? {
        substack: null
    } : value == LinkType.website ? {
        website: null
    } : value == LinkType.shopify ? {
        shopify: null
    } : value == LinkType.booking ? {
        booking: null
    } : value == LinkType.calendly ? {
        calendly: null
    } : value == LinkType.donation ? {
        donation: null
    } : value == LinkType.store ? {
        store: null
    } : value == LinkType.facebook ? {
        facebook: null
    } : value == LinkType.gumroad ? {
        gumroad: null
    } : value == LinkType.events ? {
        events: null
    } : value == LinkType.discord ? {
        discord: null
    } : value == LinkType.youtube ? {
        youtube: null
    } : value == LinkType.signal ? {
        signal: null
    } : value == LinkType.newsletter ? {
        newsletter: null
    } : value == LinkType.telegram ? {
        telegram: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberParticipantType): {
    business: null;
} | {
    organization: null;
} | {
    individual: null;
} | {
    producer: null;
} {
    return value == MemberParticipantType.business ? {
        business: null
    } : value == MemberParticipantType.organization ? {
        organization: null
    } : value == MemberParticipantType.individual ? {
        individual: null
    } : value == MemberParticipantType.producer ? {
        producer: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoteType): {
    upvote: null;
} | {
    downvote: null;
} {
    return value == VoteType.upvote ? {
        upvote: null
    } : value == VoteType.downvote ? {
        downvote: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipTier): {
    localProducer: null;
} | {
    builderMember: null;
} | {
    localSponsor: null;
} | {
    verifiedBusiness: null;
} | {
    communitySupporterTier: null;
} | {
    communityPartner: null;
} {
    return value == MembershipTier.localProducer ? {
        localProducer: null
    } : value == MembershipTier.builderMember ? {
        builderMember: null
    } : value == MembershipTier.localSponsor ? {
        localSponsor: null
    } : value == MembershipTier.verifiedBusiness ? {
        verifiedBusiness: null
    } : value == MembershipTier.communitySupporterTier ? {
        communitySupporterTier: null
    } : value == MembershipTier.communityPartner ? {
        communityPartner: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == OpportunityStatus.active ? {
        active: null
    } : value == OpportunityStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityCategory): {
    creativeArts: null;
} | {
    localFarming: null;
} | {
    other: null;
} | {
    education: null;
} | {
    technology: null;
} | {
    foodSupport: null;
} | {
    events: null;
} | {
    wellness: null;
} | {
    cleanup: null;
} | {
    delivery: null;
} | {
    youthSupport: null;
} | {
    mentorship: null;
} | {
    volunteer: null;
} {
    return value == OpportunityCategory.creativeArts ? {
        creativeArts: null
    } : value == OpportunityCategory.localFarming ? {
        localFarming: null
    } : value == OpportunityCategory.other ? {
        other: null
    } : value == OpportunityCategory.education ? {
        education: null
    } : value == OpportunityCategory.technology ? {
        technology: null
    } : value == OpportunityCategory.foodSupport ? {
        foodSupport: null
    } : value == OpportunityCategory.events ? {
        events: null
    } : value == OpportunityCategory.wellness ? {
        wellness: null
    } : value == OpportunityCategory.cleanup ? {
        cleanup: null
    } : value == OpportunityCategory.delivery ? {
        delivery: null
    } : value == OpportunityCategory.youthSupport ? {
        youthSupport: null
    } : value == OpportunityCategory.mentorship ? {
        mentorship: null
    } : value == OpportunityCategory.volunteer ? {
        volunteer: null
    } : value;
}
function to_candid_variant_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VerificationStatus): {
    verified: null;
} | {
    pending: null;
} | {
    rejected: null;
} {
    return value == VerificationStatus.verified ? {
        verified: null
    } : value == VerificationStatus.pending ? {
        pending: null
    } : value == VerificationStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipStatus): {
    pending: null;
} | {
    approved: null;
} | {
    contacted: null;
} {
    return value == MembershipStatus.pending ? {
        pending: null
    } : value == MembershipStatus.approved ? {
        approved: null
    } : value == MembershipStatus.contacted ? {
        contacted: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ConnectedPresenceLink>): Array<_ConnectedPresenceLink> {
    return value.map((x)=>to_candid_ConnectedPresenceLink_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
